version: '3'

services:
 db:
  container_name: ${CONTAINER_DB_NAME}
  image: mariadb:latest
  restart: unless-stopped
  volumes:
    - ${DB_CONF_PATH}:/etc/mysql/conf.d
    - ${DB_DATA_PATH}:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   MYSQL_DATABASE: ${WP_DB}
   MYSQL_USER: ${WP_USER}
   MYSQL_PASSWORD: ${WP_PASSWORD}
  ports:
   - ${DB_PORT}:3306

 wordpress:
  depends_on:
    - db
  container_name: ${CONTAINER_WP_NAME}
  image: wordpress:latest
  restart: unless-stopped
  volumes:
     - ${WP_CORE}:/var/www/html
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_NAME: ${WP_DB}
   WORDPRESS_DB_USER: ${WP_USER}
   WORDPRESS_DB_PASSWORD: ${WP_PASSWORD}
   WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
  ports:
   - ${HTTP_PORT}:80
   - ${HTTPS_PORT}:443
networks:
    default:
       external:
         name: ${NETWORK}
