services:
 wpdb:
  container_name: ${CONTAINER_NAME}_DB
  image: mariadb:latest
  restart: unless-stopped
  volumes:
    - ${DB_DATA_PATH}:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   MYSQL_DATABASE: ${WP_DB_NAME}
   MYSQL_USER: ${WP_DB_USER}
   MYSQL_PASSWORD: ${WP_DB_USER_PASSWORD}

 wordpress:
  depends_on:
    - wpdb
  container_name: ${CONTAINER_NAME}_WP
  image: wordpress:5.6-php7.3-apache
  restart: unless-stopped
  volumes:
     - ${PHP_INI}:/usr/local/etc/php/conf.d/php.ini
     - ${WP_HTML}:/var/www/html
  environment:
   WORDPRESS_DB_HOST: wpdb:3306
   WORDPRESS_DB_NAME: ${WP_DB_NAME}
   WORDPRESS_DB_USER: ${WP_DB_USER}
   WORDPRESS_DB_PASSWORD: ${WP_DB_USER_PASSWORD}
   WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
  ports:
   - ${HTTP_PORT}:80
